### ISSUE TITLE
List of files to ignore

### ISSUE THREAD

**Issue by kentaasvang** [kentaasvang/kentaasvang.ServerWorker#11]
should add feature to configure files that the worker should ignore when cleaning up public_dir. Like **venv** for python virtual environments.

could be specified like this:
```
services:
  - name: servicename
    publish_dir: "/publish"
    public_dir: "/public"
    ignore: 
      - "venv"
      - "appsettings.json"
```
