### ISSUE TITLE
run commands after deployment

### ISSUE THREAD

**Issue by kentaasvang** [kentaasvang/kentaasvang.ServerWorker#12]
would be usefull to specify commands that should be run after deployment

```
services:
  - name: servicename
    public_dir: "/public"
    publish_dir: "/publish"
    commands:
      - "pip install -r requirements.txt"
      - "systemctl restart service"
```
